baseurl = "https://www.glowisle.me/"
title = "ğŸ„ æ˜ å±¿"
hasCJKLanguage = true
enableRobotsTXT = true
pagination.pagerSize = 5
languageCode = "zh-CN"
copyright = "Copyright Â© 2024, GlowIsle."

[outputFormats]
  [outputFormats.RSS]
    baseName = "atom"  # æ›´æ”¹æ–‡ä»¶åï¼ˆä¸å¸¦æ‰©å±•åï¼‰
    mediaType = "application/rss+xml"
    isPlainText = true
    rel = "alternate"
    protocol = "http://"
    path = ""  # ä¿æŒè·¯å¾„åœ¨æ ¹ç›®å½•

[markup]
  [markup.highlight]
    style = "onedark"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
    category = "categories"
    tag = "tags"

[menu]

[[menu.main]]
    name = "åˆ†ç±»"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "å‹äºº"
    url = "/links"
    weight = 3

[[menu.main]]
    name = "å½’æ¡£"
    url = "/archives"
    weight = 4

[[menu.main]]
    name = "å…³äº"
    url = "/about"
    weight = 5

[params]
	upvote = true
    upvoteURL = "https://upvote.glowisle.me/"
	description = "å…³äºäº’è”ç½‘ã€ä¹¦ç±ã€ç”Ÿæ´»çäº‹ä»¥åŠé‚£äº›ä¸€é—ªè€Œè¿‡çš„å¿µå¤´ã€‚è®¡ç®—æœºæŠ€æœ¯ & è¯»ä¹¦æ„Ÿæ‚Ÿ & æ—¥å¸¸éšç¬”ã€‚æ˜ å±¿(GlowIsle)"
	postSearch = false
	groupByYear = true
	toc = true
	showPostCount = true
	favicon = "/favicon.png"
    hideMadeWithLine = true
    imageZoom = true

  [params.author]
    name = "äº”è‘‰åœ°éŒ¦"
    email = "i@glowisle.me"
