baseURL = "https://www.glowisle.me/"
title = "映屿"
hasCJKLanguage = true
enableRobotsTXT = true
pagination.pagerSize = 5
languageCode = "zh-CN"
copyright = "Copyright © 2024, GlowIsle."

[outputFormats]
  [outputFormats.RSS]
    baseName = "atom"  # 更改文件名（不带扩展名）
    mediaType = "application/rss+xml"
    isPlainText = true
    rel = "alternate"
    protocol = "http://"
    path = ""  # 保持路径在根目录

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "onedark"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"

    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
      xHTML = false

[taxonomies]
    category = "categories"
    tag = "tags"

[menu]

[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

[[menu.main]]
    name = "友人"
    url = "/links/"
    weight = 3

[[menu.main]]
    name = "归档"
    url = "/archives"
    weight = 3

[[menu.main]]
    name = "书单"
    url = "/readings"
    weight = 3

[[menu.main]]
    name = "关于"
    url = "/about"
    weight = 6

[params]
	upvote = true
    upvoteURL = "https://upvote.glowisle.me/"
	description = "关于互联网、书籍、生活琐事以及那些一闪而过的念头。计算机技术 & 读书感悟 & 日常随笔。映屿(GlowIsle)"
	postSearch = false
	groupByYear = true
	toc = true
	showPostCount = true
	favicon = "/favicon.png"
    hideMadeWithLine = true
    imageZoom = true

  [params.author]
    name = "五葉地錦"
    email = "i@glowisle.me"

  [params.footer]
    content = "© 2024 - 2026 | Made with ❤️ by Verdant."
